name: sample flow

on:
  push:

jobs:
  with-action:
    runs-on: ubuntu-latest
    needs: [reusable-workflow]
    steps:
      - id: vars
        uses: hanseartic/actions/short-vars@main
        with:
          ref-prefix: pre
          ref-suffix: action
      - run: |
          echo '${{ toJSON(steps.vars.outputs) }}' | jq .
      - run: |
          echo '${{ toJSON(needs.reusable-workflow.outputs) }}' | jq .
  reusable-workflow:
    uses: hanseartic/actions/.github/workflows/short-vars.yml@main
    with:
      ref-prefix: pre
      ref-suffix: workflow
