name: sample flow

on:
  push:
  pull_request:

jobs:
  with-action:
    runs-on: ubuntu-latest
    needs: [reusable-workflow]
    steps:
      - id: vars
        uses: hanseartic/actions/short-vars@main
        with:
          ref-prefix: pre
          ref-suffix: action
      - run: |
          echo '${{ toJSON(steps.vars.outputs) }}' | jq .
      - run: |
          echo '${{ toJSON(needs.reusable-workflow.outputs) }}' | jq .
  reusable-workflow:
    uses: hanseartic/actions/.github/workflows/short-vars.yml@main
    with:
      sha-length: 10
      ref-keep-before: '/'
      ref-keep-after: github.com
      ref: 'dependabot/npm_service/some/nested/folder/that/makes-the-path-long-src-github.com-package_ns-package_name-1.2.3'
