name: sample flow

on:
  push:
  pull_request:

jobs:
  with-action:
    runs-on: ubuntu-latest
    needs: [reusable-workflow]
    steps:
      - id: vars
        uses: hanseartic/actions/short-vars@main
        with:
          ref-prefix: pre
          ref-suffix: action
      - run: |
          echo "### action" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '${{ toJSON(steps.vars.outputs) }}' | jq . >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - run: |
          echo "### reusable workflow" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo '${{ toJSON(needs.reusable-workflow.outputs) }}' | jq . >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
      - run: |
          echo "### artifact" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ toJSON(steps.vars.outputs) }}" >> $GITHUB_STEP_SUMMARY
          echo '```' >> $GITHUB_STEP_SUMMARY
          echo "${{ toJSON(steps.vars.outputs) }}" >> short-vars.json
      - uses: actions/upload-artifact@v3
        with:
          name: short-vars
          path: ${{ github.workspace }}/short-vars.json
  reusable-workflow:
    uses: hanseartic/actions/.github/workflows/short-vars.yml@main
    with:
      sha-length: 10
      ref-keep-before: '/'
      ref-keep-after: github.com
      ref: 'dependabot/npm_service/some/nested/folder/that/makes-the-path-long-src-github.com-package_ns-package_name-1.2.3'
